openapi: 3.0.1
info:
  title: my app
  description: my api
  version: "1.0"
paths:
  /account:
    post:
      operationId: createNewAccount
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAccountDto'
        required: true
      responses:
        "200":
          description: createNewAccount 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountDto'
  /account/{accountNumber}:
    get:
      operationId: getAccountByAccountNumber
      parameters:
      - name: accountNumber
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: getAccountByAccountNumber 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountDto'
  /creditCardBill:
    patch:
      operationId: closeCreditCardBill
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CloseCreditCardBillDto'
        required: true
      responses:
        "200":
          description: closeCreditCardBill 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpStatus'
  /creditCardBill/{accountNumber}/{month}/{year}:
    get:
      operationId: closeCreditCardBill
      parameters:
      - name: accountNumber
        in: path
        required: true
        schema:
          type: string
      - name: month
        in: path
        required: true
        schema:
          type: string
      - name: year
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: closeCreditCardBill 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ListPaymentTransactionDto'
  /payment:
    post:
      operationId: createNewAccount
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentTransactionDto'
        required: true
      responses:
        "200":
          description: createNewAccount 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenBillDto'
components:
  schemas:
    AccountDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        accountNumber:
          type: string
        name:
          type: string
        document:
          type: string
    CloseCreditCardBillDto:
      required:
      - accountNumber
      - creditCardBillId
      type: object
      properties:
        creditCardBillId:
          type: integer
          format: int64
        accountNumber:
          type: string
    CreateAccountDto:
      required:
      - document
      - name
      type: object
      properties:
        name:
          minLength: 6
          type: string
        document:
          maxLength: 11
          minLength: 11
          type: string
    HttpStatus:
      type: string
      enum:
      - CONTINUE
      - SWITCHING_PROTOCOLS
      - PROCESSING
      - OK
      - CREATED
      - ACCEPTED
      - NON_AUTHORITATIVE_INFORMATION
      - NO_CONTENT
      - RESET_CONTENT
      - PARTIAL_CONTENT
      - MULTI_STATUS
      - ALREADY_IMPORTED
      - IM_USED
      - MULTIPLE_CHOICES
      - MOVED_PERMANENTLY
      - FOUND
      - SEE_OTHER
      - NOT_MODIFIED
      - USE_PROXY
      - SWITCH_PROXY
      - TEMPORARY_REDIRECT
      - PERMANENT_REDIRECT
      - BAD_REQUEST
      - UNAUTHORIZED
      - PAYMENT_REQUIRED
      - FORBIDDEN
      - NOT_FOUND
      - METHOD_NOT_ALLOWED
      - NOT_ACCEPTABLE
      - PROXY_AUTHENTICATION_REQUIRED
      - REQUEST_TIMEOUT
      - CONFLICT
      - GONE
      - LENGTH_REQUIRED
      - PRECONDITION_FAILED
      - REQUEST_ENTITY_TOO_LARGE
      - REQUEST_URI_TOO_LONG
      - UNSUPPORTED_MEDIA_TYPE
      - REQUESTED_RANGE_NOT_SATISFIABLE
      - EXPECTATION_FAILED
      - I_AM_A_TEAPOT
      - ENHANCE_YOUR_CALM
      - UNPROCESSABLE_ENTITY
      - LOCKED
      - FAILED_DEPENDENCY
      - UNORDERED_COLLECTION
      - UPGRADE_REQUIRED
      - PRECONDITION_REQUIRED
      - TOO_MANY_REQUESTS
      - REQUEST_HEADER_FIELDS_TOO_LARGE
      - NO_RESPONSE
      - BLOCKED_BY_WINDOWS_PARENTAL_CONTROLS
      - UNAVAILABLE_FOR_LEGAL_REASONS
      - REQUEST_HEADER_TOO_LARGE
      - INTERNAL_SERVER_ERROR
      - NOT_IMPLEMENTED
      - BAD_GATEWAY
      - SERVICE_UNAVAILABLE
      - GATEWAY_TIMEOUT
      - HTTP_VERSION_NOT_SUPPORTED
      - VARIANT_ALSO_NEGOTIATES
      - INSUFFICIENT_STORAGE
      - LOOP_DETECTED
      - BANDWIDTH_LIMIT_EXCEEDED
      - NOT_EXTENDED
      - NETWORK_AUTHENTICATION_REQUIRED
      - CONNECTION_TIMED_OUT
    ListPaymentTransactionDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        businessEstablishment:
          type: string
        value:
          type: number
          format: double
        valueOfInstallments:
          type: number
          format: double
        numberOfInstallments:
          type: integer
          format: int32
        numberOfCurrentInstallment:
          type: integer
          format: int32
        accountNumber:
          type: string
        creditCardBillId:
          type: integer
          format: int64
        transactionDate:
          type: string
          format: date-time
    OpenBillDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
    PaymentTransactionDto:
      required:
      - accountNumber
      - businessEstablishment
      - numberOfInstallments
      - transactionDate
      - value
      - valueOfInstallments
      type: object
      properties:
        businessEstablishment:
          minLength: 3
          type: string
        value:
          type: number
          format: double
        valueOfInstallments:
          type: number
          format: double
        numberOfInstallments:
          type: integer
          format: int32
        accountNumber:
          type: string
        transactionDate:
          type: string
          format: date-time
